[build]
  command = "npm install @supabase/supabase-js && node build/generateMarkdown.js && hugo"
  publish = "public"
  functions = "non_existent"

  [[redirects]]
    from = "/admin/*"
    to = "https://jocular-daffodil-cfecd4.netlify.app/:splat"
    status = 200
    force = true

  [[redirects]]
    from = "/admin"
    to = "https://netlify-name-thing.netlify.app"
    status = 200
    force = true

